# Generated by Django 6.0.7 on 2026-07-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_pastquestion_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastquestion',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
