# Generated by Django 6.0.7 on 2026-08-04 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_pastquestion_question_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastquestion',
            options={'ordering': ['-year']},
        ),
    ]
